import packageInfo from '../../package.json' with { type: 'json' };

export const generatorName = packageInfo.name;
export const generatorVersion = packageInfo.version;

export function generatedHeader(): string {
  return [
    '/* tslint:disable */',
    '/* eslint-disable */',
    `// Auto generated by ${generatorName} v${generatorVersion}. Do not edit manually.`,
  ].join('\n');
}
